const LIST_LOADING = 'LIST_LOADING';
const LIST_LOADED = 'LIST_LOADED';
const CHANGE_OFFSET = 'CHANGE_OFFSET';
const ARTICLE_LOADED = 'ARTICLE_LOADED';
const USER_DATA_LOADED = 'USER_DATA_LOADED';

export { LIST_LOADING, LIST_LOADED, CHANGE_OFFSET, ARTICLE_LOADED, USER_DATA_LOADED };
